// Generated by CoffeeScript 1.6.3
(function() {
  var pokemon, types;

  types = [];

  pokemon = [];

  $.ajax({
    async: false,
    url: "/poketeam/js/app/pokemon_db.json",
    dataType: "json",
    success: function(data) {
      return types = data["types"];
    }
  });

  $.ajax({
    async: false,
    url: "/poketeam/js/app/pokemon.json",
    dataType: "json",
    success: function(data) {
      return pokemon = data["pokemon"];
    }
  });

  console.log(pokemon);

  $(function() {
    var pokemon_list;
    pokemon_list = pokemon;
    return $("#autocomplete").autocomplete({
      source: pokemon
    });
  });

}).call(this);
